#!/usr/bin/perl -w

my ($remote) = @ARGV;

die "A remote host is required" if !$remote;

my $path   = normalize_current_directory();
my $parent = get_parent_directory($path);

my $output = `rsync -av $path $remote:$parent --exclude='.svn' --exclude='.git'`;
print "$output\n";


sub normalize_current_directory {
    $whoami = trim(`whoami`);           # keugene
    $pwd    = trim(`pwd`);              # /Users/keugene/some/directory
    @paths  = split /$whoami/, $pwd;    # ('/Users/', '/some/directory')
    $path   = pop @paths;               # /some/directory

    return "~$path";                    # ~/some/directory
}

sub get_parent_directory {
    my ($current) = @_;
    @dir_names = split /\//, $current;
    pop @dir_names;

    return join '/', @dir_names;
}

sub trim {
    my ($str) = @_;
    $str =~ s/^\s+//;
    $str =~ s/\s+$//;
    return $str;
}
