#!/bin/bash

ln -s ~/repository/ubiquitous/vimrc    ~/.vimrc
ln -s ~/repository/ubiquitous/bashrc   ~/.bashrc
ln -s ~/repository/ubiquitous/bashrc   ~/.bash_profile
ln -s ~/repository/ubiquitous/inputrc  ~/.inputrc
