#!/bin/bash

ln -sf $(pwd)/vimrc    ~/.vimrc
ln -sf $(pwd)/screenrc ~/.screenrc
ln -sf $(pwd)/bashrc   ~/.bashrc
ln -sf $(pwd)/bashrc   ~/.bash_profile
ln -sf $(pwd)/inputrc  ~/.inputrc
ln -sf $(pwd)/vim      ~/.vim

# mkdir -p ~/.ssh && ln -sf $(pwd)/ssh_config ~/.ssh/config

source ~/.bashrc
